env:
  browser: true
  es6: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
parser: 'babel-eslint'
#plugins: ['react']
rules:
  indent:
    - error
    - 4
    - { "SwitchCase": 1 }
  linebreak-style:
    - error
    - unix
  quotes: off
  semi: off
  no-console: off
  react/prop-types: off
  react/display-name: off
settings:
  react:
    version: 'detect'
