env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
    - { "SwitchCase": 1 }
  linebreak-style:
    - error
    - unix
  quotes: off
  semi: off
  no-console: off
  react/prop-types: off
  react/display-name: off
