# Language and env

language: node_js
node_js: 'node'
cache: npm

# Travis Lifecycle
before_script: npm run build-demo

# Ajoute les artéfacts au déploiement
after_success:
- mkdir deploy
- cp index.html ./dist
- cp -rf build ./dist && rm dist/.gitignore
- cp -rf public ./dist
- cp -rf images ./dist

deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GH_TOKEN
  keep-history: false
  local-dir: dist
  on:
    branch: master

# Other configs

git:
  depth: 10
