# Language and env

language: node_js
node_js: 'node'
cache: npm

# Travis Lifecycle
before_script: npm run build-demo

# Ajoute les artéfacts au déploiement
on_success:
- rm build/.gitignore

deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GH_TOKEN
  keep-history: false
  local-dir: .
  on:
    branch: master

# Other configs

git:
  depth: 10
